name: Build Container Image

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Build package
      run: |
        python setup.py sdist
    - name: Publish to Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: mkell43/pgdatadiff
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
